spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/agroayacucho}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

server.port=${PORT:8081}
